# Generated by Django 6.0.3 on 2026-03-29 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaotreino',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='em_andamento', max_length=20),
        ),
        migrations.CreateModel(
            name='ExecucaoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.execucaotreino')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercicio')),
            ],
        ),
    ]
