# Generated by Django 6.0.3 on 2026-04-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('vencida', 'Vencida')], default='em_andamento', max_length=20),
        ),
    ]
