# Generated by Django 6.0.3 on 2026-04-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_meta_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
