# Generated by Django 6.0.3 on 2026-04-11 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_meta_data_conclusao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_principal', models.CharField(choices=[('emagrecimento', 'Emagrecimento'), ('ganho_massa', 'Ganho de massa'), ('reducao_cintura', 'Redução de cintura')], max_length=30)),
                ('objetivo_descricao', models.CharField(blank=True, max_length=200)),
                ('altura_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atleta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicaoAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('braco_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cintura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peito_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coxa_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='core.atleta')),
            ],
            options={
                'ordering': ['-data_registro', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='atleta',
            constraint=models.CheckConstraint(condition=models.Q(('altura_cm__gt', 0)), name='atleta_altura_positiva'),
        ),
        migrations.AddConstraint(
            model_name='medicaoatleta',
            constraint=models.CheckConstraint(condition=models.Q(('peso_kg__gt', 0)), name='medicao_peso_positivo'),
        ),
        migrations.AddConstraint(
            model_name='medicaoatleta',
            constraint=models.CheckConstraint(condition=models.Q(('braco_cm__gt', 0), ('braco_cm__isnull', True), _connector='OR'), name='medicao_braco_positivo_ou_nulo'),
        ),
        migrations.AddConstraint(
            model_name='medicaoatleta',
            constraint=models.CheckConstraint(condition=models.Q(('cintura_cm__gt', 0), ('cintura_cm__isnull', True), _connector='OR'), name='medicao_cintura_positiva_ou_nula'),
        ),
        migrations.AddConstraint(
            model_name='medicaoatleta',
            constraint=models.CheckConstraint(condition=models.Q(('peito_cm__gt', 0), ('peito_cm__isnull', True), _connector='OR'), name='medicao_peito_positivo_ou_nulo'),
        ),
        migrations.AddConstraint(
            model_name='medicaoatleta',
            constraint=models.CheckConstraint(condition=models.Q(('coxa_cm__gt', 0), ('coxa_cm__isnull', True), _connector='OR'), name='medicao_coxa_positiva_ou_nula'),
        ),
    ]
