# Generated by Django 6.0.3 on 2026-04-14 00:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_atleta_medicaoatleta_atleta_atleta_altura_positiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
